{"ERROR_MESSAGE": "Traceback (most recent call last):\n  File \"F:\\projects\\pythonProjects\\coppellia_project_1\\src\\execution_scripts\\iterator.py\", line 99, in startGyroIteration\n    self.analyser.onGyroIteration()\n  File \"F:\\projects\\pythonProjects\\coppellia_project_1\\src\\ananlysing_scripts\\analyser.py\", line 107, in onGyroIteration\n    self.iterationData.gyroData = self.hardwareExecutor.readGyro()\n                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"F:\\projects\\pythonProjects\\coppellia_project_1\\src\\execution_scripts\\hardware_executor.py\", line 181, in readGyro\n    return self.gyroscopeEmulator.update(euler_angles)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"F:\\projects\\pythonProjects\\coppellia_project_1\\src\\execution_scripts\\emulation\\emulation_tools.py\", line 17, in update\n    logError(f\"Gyro emulator dt = {1/dt}\")\n                                   ~^~~\nZeroDivisionError: float division by zero\n", "IS_IN_MAIN": false, "CURRENT_DIRECTION": 0.0, "CURRENT_ID": -1, "CURRENT_ANGLE": 0.0, "READ_IDS": [], "STATE": "ROTATING"}